name: Google Test Example

on:
  workflow_dispatch:
    

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Google Test
        uses: ./.github/gtest/action.yml
